# Generated by Django 5.0.3 on 2024-04-03 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=511, verbose_name="advert's title")),
                ('content', models.TextField(verbose_name='content')),
                ('icon', models.ImageField(upload_to='', verbose_name='icon for preview')),
                ('category', models.IntegerField(choices=[(1, 'Танки'), (2, 'Хилы'), (3, 'Дд'), (4, 'Торговцы'), (5, 'Гилдмастеры'), (6, 'Квестгиверы'), (7, 'Кузнецы'), (8, 'Кожевники'), (9, 'Зельевары'), (10, 'Мастера Заклинаний')], verbose_name='category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Respond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='comment')),
                ('advert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advapp.advert', verbose_name='advert')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
