# Generated by Django 5.0.3 on 2024-04-03 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respond',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date of creation'),
            preserve_default=False,
        ),
    ]
