# Generated by Django 5.0.3 on 2024-04-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0002_advert_date_creation_respond_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category')),
            ],
        ),
        migrations.AlterField(
            model_name='advert',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='icon for preview'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advapp.category', verbose_name='category'),
        ),
    ]
