# Generated by Django 5.0.3 on 2024-04-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='icon',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='icon for preview'),
        ),
    ]
