# Generated by Django 5.0.3 on 2024-04-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0006_alter_advert_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
