# Generated by Django 5.0.3 on 2024-04-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0007_respond_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='icon',
            field=models.ImageField(default='media/blanc.png', upload_to='', verbose_name='icon for preview'),
        ),
    ]
