# Generated by Django 5.0.3 on 2024-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0008_alter_advert_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='icon',
            field=models.ImageField(default='blanc.png', upload_to='', verbose_name='icon for preview'),
        ),
    ]
