# Generated by Django 5.0.3 on 2024-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0009_alter_advert_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='icon',
            field=models.ImageField(default='icons/blanc.png', upload_to='icons', verbose_name='icon for preview'),
        ),
    ]
