# Generated by Django 5.0.3 on 2024-04-08 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advapp', '0011_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advapp.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='icon',
            field=models.ImageField(default='icons/blanc.png', upload_to='icons', verbose_name='Изображение для превью'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=511, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='respond',
            name='advert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advapp.advert', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='respond',
            name='content',
            field=models.TextField(verbose_name='Отклик'),
        ),
        migrations.AlterField(
            model_name='respond',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
